#ifndef COMMANDS_HASHES_H_INCLUDED
#define COMMANDS_HASHES_H_INCLUDED

#define MOV_HASH 3647
#define MVI_HASH 3221
#define DEC_HASH 2894
#define INC_HASH 2953

#endif // COMMANDS_HASHES_H_INCLUDED
